### ISSUE TITLE
Issue with calculations causing glitches

### ISSUE THREAD

**Issue by Chappie74** [bharathraj-e/responsive_ui#5]
# Description of issue
I have two responsive containers that I am displaying, defined below:

```dart
Responsive(
              children: [
                Div(
                  divison: const Division(colS: 3, colM: 3, colL: 1, colXL: 1),
                  child: Container(
                    padding: EdgeInsets.zero,
                    margin: EdgeInsets.zero,
                    height: 100,
                    color: Colors.black,
                  ),
                ),
                Div(
                    divison:
                        const Division(colS: 9, colM: 9, colL: 11, colXL: 11),
                    child: Container(
                      height: 100,
                      padding: EdgeInsets.zero,
                      margin: EdgeInsets.zero,
                      color: Colors.red,
                    )),
              ],
            ),
```

It appears as though, when all of the divisions add up to 12 perfectly, the calculations that occurs to determine the width of each widget causes glitches. 

<img src="https://i.imgur.com/CI2R4OA.gif" width="700"/>

Upon further investigation, it seems to be an issue with the calculations of the [childWidth](https://github.com/bharathraj-e/responsive_ui/blob/f4428f844157e316846254afa22655d8fa1e2629/lib/src/div.dart#L47)
There are some cases (due to the division/multiplication of floating point numbers) that the child width ends up being a few 10ths of a pixels wider than it should be causing the wrap to put it into the bottom section. This causes the sum of all the box widths to end up being a bit larger than the total available width (provided by [layout builder](https://github.com/bharathraj-e/responsive_ui/blob/f4428f844157e316846254afa22655d8fa1e2629/lib/src/div.dart#L45))

I have a working solution and will open a pull request.

**Comment by bharathraj-e** [comment]
Hi @Chappie74 

Thanks for pointing the issue and providing the solution. Your PR #6 has been merged.

 I will release this fix in pub.dev soon.
